name: Deploy para Vps

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout do Repositório"
      uses: actions/checkout@v4

    - name: "Instalação do Node.js"
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: "Instalação das Dependências"
      run: npm install

    - name: "Build do Projeto"
      run: npm run build

    - name: "Deploy do Projeto"
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        TARGET: ${{ secrets.TARGET }}