name: Deploy para VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Listar arquivos no diretório atual
        run: ls -la

      - name: Navegar para o diretório do projeto
        run: cd react-teste-ing

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Versão LTS atual do Node.js

      - name: Instalar dependências
        run: npm install

      - name: Construir o projeto
        run: npm run build

      - name: Deploy para VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.TARGET }}
            git pull origin prod
            npm install --production
            pm2 restart all
