name: Deploy para VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 

      - name: Instalar dependências
        run: npm install
        working-directory: react-teste=ing

      - name: Construir o projeto
        run: npm run build
        working-directory: react-teste=ing

      - name: Deploy para VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            if [ ! -d "/Frontend-do-Quack/react-teste=ing" ]; then
              echo "Erro: Diretório /Frontend-do-Quack/react-teste=ing não encontrado"
              exit 1
            fi
            cd /Frontend-do-Quack/react-teste=ing
            if [ ! -d ".git" ]; then
              echo "Erro: Não é um repositório Git válido"
              exit 1
            fi
            git pull origin prod
            if [ ! -f "react-teste=ing/package.json" ]; then
              echo "Erro: Arquivo package.json não encontrado"
              exit 1
            fi
            npm install --production --prefix react-teste=ing
            if ! command -v pm2 &> /dev/null; then
              echo "Erro: pm2 não encontrado"
              exit 1
            fi
            pm2 restart all